apiVersion: v1
kind: Service
metadata:
  name: password-manager-service
spec:
  selector:
    app: password-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort
